---
- name: playbook to copy file
  hosts: all
  become: true
  tasks:
  - name: copy module
    copy:
     src: /home/ansadmin/index.html
     dest: /home/ansadmin
     mode: 0600
     owner: karthik

