---
- name: Playbook to install 
  hosts: all
  become: true
  
  tasks:
  - name: install java on Redhat
    yum:
     name: java
     state: installed
    when: ansible_os_family == "Redhat"
    
  - name: install java on Debian
    yum:
     name: default-jdk
     state: present
    when: ansible_os_family == "Debian"

  - name: download tomcat
    get_url:
     url: https://dlcdn.apache.org/tomcat/tomcat-8/v8.5.81/bin/apache-tomcat-8.5.81.tar.gz
     dest: /opt
  
  - name: install tomcat
    yum:
     name: tomcat
     state: installed

  - name: extract tomcat
    unarchive:
     src: /opt/apache-tomcat-8.5.81.tar.gz
     dest: /opt
     remote_src: yes

  - name: Add executable permissions
    file:
     path: /opt/apache-tomcat-8.5.81/bin/startup.sh
     mode: 0777

  - name: start tomcat service
    shell: nohup ./startup.sh
    args: 
     chdir: /opt/apache-tomcat-8.5.81/bin
...
