---
- name: install packages
  hosts: all
  become: true
  tasks:
  - name: install tree package
    yum:
      name: tree
      state: installed
    -name: install git package
      yum:
       name: git
       state: installed
