---
- name: uninstall httpd
  hosts: all
  become: true
  tasks:
  - name: stop httpd service
    service:
      name: httpd
      state: stopped

  - name: uninstall htppd
    yum:
      name: httpd
      state: removed
