---
- name: playbok for while condition of httpd
  hosts: all
  become: true
  
  tasks:
  - name: install htttpd
    yum:
     name: httpd
     state: installed
    when: ansible_os_family == "RedHat"

  - name: start httpd 
    service:
     name: httpd
     state: started
    when: ansible_os_family == "RedHat"

  - name: install apache2
    apt:
     name: install apache2
     state: installed
    when: ansible_os_family == "Debian"

  - name: start apache2
    service:
     name: apache2
     state: started
    when: ansible_os_family == "Debian"
...
