---
# handlers file for roles-apache-setup
- name: start httpd
  service:
    name: httpd
    state: started
  when: ansible_os_family == "RedHat"
  notify: start httpd
- name: start apache2
  service:
    name: apache2
    state: started
  when: ansible_os_family == "Debian"
  notify: start apache2
